name: ccloud-sdk-go-v2
lang: go
lang_version: "1.25.7"
git:
  enable: true
github:
  enable: true
semaphore:
  enable: true
  pipeline_enable: false
  branches:
    - master
    - /^v\d+\.\d+\.\d+$/
  managed_sections:
    - version
    - name
    - agent
    - global_job_config
make:
  enable: true
  enable_updates: true
  update_makefile: false
